### ISSUE TITLE
为什么使用对比损失函数会报内存错误？我是20G的显卡

### ISSUE THREAD

**Issue by BLUE811420** [ZhengxiangShi/SelfContrastiveLearningRecSys#3]

**Comment by ShiZhengyan** [comment]
Hi 感谢您的问题。请问您是否能分享一下报错信息？如果您设置的`--sampled_item_size`这个参数太大也是有可能的，不妨把这个值调小试试。

**Comment by BLUE811420** [comment]
好的，已经解决啦，感谢🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月19日 16:15 |
| 收件人 | ZhengxiangShi/SelfContrastiveLearningRecSys ***@***.***> |
| 抄送人 | Xiao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ZhengxiangShi/SelfContrastiveLearningRecSys] 为什么使用对比损失函数会报内存错误？我是20G的显卡 (Issue #3) |

Hi 感谢您的问题。请问您是否能分享一下报错信息？如果您设置的--sampled_item_size这个参数太大也是有可能的，不妨把这个值调小试试。
